Add/remove convenience methods on Configuration
relab/gorums pull request #132
Opened 2021-03-18 15:07 UTC by meling

This adds methods Add, Remove, AddNodes, RemoveNodes to gorums.Configuration and correspondingly to dev.Configuration via struct embedding and method forwarding as needed.

This doesn't actually implement what was proposed in #28 exactly but gives the flexibility to add/remove nodes/configurations to/from an existing configuration. We still need to use the mgr.NewConfiguration method to actually produce the new configuration, so that we can pass in the QuorumSpec.

Closes #28.

2021-03-18 16:37 UTC, meling commented
The current design in this PR allows this:
```golang
	c3, err := mgr.NewConfiguration(
		newQSpec(c1.Size()+c2.Size()),
		c1.Add(c2),
	)
```

However, we could do this instead:
```golang
	c3, err := c1.Add(c2, newQSpec(c1.Size()+c2.Size()))
```

This is clearly shorter, and it doesn't require access to the `mgr` to create new configurations from existing ones.

The benefit of the first approach is that we could also do:
```golang
	newNodeList := c1.Add(c2)
	c3, err := mgr.NewConfiguration(
		newQSpec(newNodeList.Size()),
		newNodeList,
	)
```

It is also more clear that `mgr.NewConfiguration` returns a `Configuration`, as opposed to `c1.Add(c2...)`.

As these are really just convenience methods, I prefer to keep only one `Add` method. I'm leaning towards the current approach, but want to hear other opinions. @Raytar @leandernikolaus @s111 @tormoder

2021-03-25 20:06 UTC, meling commented
Alternative naming for `Add`:
```golang
proto.Add(c1, c2)
proto.With(c1, c2)
proto.WithConfigurations(c1, c2)
proto.Combine(c1, c2)
proto.Merge(c1, c2)

c1.Add(c2)
c1.With(c2)
c1.WithConfiguration(c2)
c1.Combine(c2)
c1.Merge(c2)
```

2021-03-27 10:16 UTC, Raytar requested changes

2021-03-27 10:16 UTC, Raytar commented on tests/config/config_test.go
> +func TestConfig(t *testing.T) {
Some comments explaining the test would be helpful here I think. I looks like the `setup()` function is creating a new configuration with new nodes, such that each configuration created with `setup()` contain separate sets of nodes? Then you are testing the `With()` and `Without()` on these configurations?

2021-03-27 10:23 UTC, Raytar commented
What about `And()` and `Except()`?

```go
// c3 will contain the nodes of c1 and c2
c3, err := mgr.NewConfiguration(c1.And(c2))
// c3 will contain the nodes of c3 except the nodes of c2
c4, err := mgr.NewConfiguration(c3.Except(c2))
```

2021-03-27 14:44 UTC, Raytar approved these changes
LGTM!

2021-03-27 15:50 UTC, merged