fix: node RPCCall returns nil instead of error
relab/gorums pull request #167
Opened 2024-02-01 16:31 UTC by vidarandrebo

Fixed a bug where an error was not returned from node.RPCCall
Added tests for all return paths in RPCCall function.

2024-02-01 16:32 UTC, vidarandrebo commented on rpc.go
> -			return nil, err
err is always nil here

2024-02-01 16:32 UTC, vidarandrebo commented on rpc.go
> -		return resp, ctx.Err()
resp is always nil here

2024-02-02 09:58 UTC, meling requested changes
Looks great! A few minor things.

2024-02-02 09:58 UTC, meling commented on rpc.go
>  		if r.err != nil {
Here we can simply return without the proceeding `if`:
```go
return r.msg, r.err
```
Or did I miss something? The tests still pass with this version.

2024-02-02 09:58 UTC, meling commented on rpc_test.go
> +func rpcTestMgr() *dummy.Manager {
Maybe a better name for this helper would be `gorumsTestMgr` or something?

2024-02-02 13:36 UTC, meling approved these changes

2024-02-02 13:36 UTC, merged